name: node.js
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-varsion: [ 18.16.1 ]
    steps:
      - uses: actions/checkout@v4
      - name: Starting node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build project
        run: npm run build